// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notification.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Notification.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SmartPushDbContext))]
    [Migration("20260714024616_InitialSmartPush")]
    partial class InitialSmartPush
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("smart_push")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Notification.Domain.Models.SmartPushLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)")
                        .HasColumnName("body");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("channel");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("dedup_key");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date")
                        .HasColumnName("local_date");

                    b.Property<bool>("Opened")
                        .HasColumnType("boolean")
                        .HasColumnName("opened");

                    b.Property<DateTimeOffset>("SentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at_utc");

                    b.Property<string>("Title")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("title");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trigger");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_smart_push_log");

                    b.HasIndex("DedupKey")
                        .IsUnique()
                        .HasDatabaseName("ux_sps_log_dedup");

                    b.HasIndex("UserId", "LocalDate")
                        .HasDatabaseName("ix_sps_log_user_date");

                    b.ToTable("smart_push_log", "smart_push");
                });

            modelBuilder.Entity("Notification.Domain.Models.SmartPushSchedule", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateOnly?>("DayKeyLocal")
                        .HasColumnType("date")
                        .HasColumnName("day_key_local");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTimeOffset?>("LastSentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sent_at_utc");

                    b.Property<string>("LastTrigger")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_trigger");

                    b.Property<DateTimeOffset?>("NextFireAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_fire_at_utc");

                    b.Property<short>("SentToday")
                        .HasColumnType("smallint")
                        .HasColumnName("sent_today");

                    b.Property<short>("SlotsPerDay")
                        .HasColumnType("smallint")
                        .HasColumnName("slots_per_day");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_smart_push_schedule");

                    b.HasIndex("NextFireAtUtc")
                        .HasDatabaseName("ix_sps_due")
                        .HasFilter("enabled = true AND next_fire_at_utc IS NOT NULL");

                    b.ToTable("smart_push_schedule", "smart_push");
                });
#pragma warning restore 612, 618
        }
    }
}
